### ISSUE TITLE
Version of Lua, Torch // demo issue

### ISSUE THREAD

**Issue by gpolaert** [facebookresearch/multipathnet#2]
Hi everyone,

I tried to run the demo, but I had this issue when the script is loading the sharpmask model.
```/usr/local/bin/luajit: /usr/local/share/lua/5.1/torch/File.lua:301: Failed to load function from bytecode: (binary): cannot load incompatible bytecode```

If I think it's a probably because I haven't the right version of lua or torch. 
Is that possible? If yes, which one I have to install.

Thanks, Guillaume

**Comment by szagoruyko** [comment]
there was a bug in cudnn.torch that was saving `accGradParameters` function inside every convolution. You can update your torch with `luarocks install torch` as it should be fixed to ignore such functions on loading via https://github.com/torch/torch7/pull/748

if it doesn't help @poliveirap you could run `net:apply(function(x) x.accGradParameters = nil end)` on sharpmask and reupload the model

**Comment by gpolaert** [comment]
Still have the issue, with a smarter error message :)
```
Warning: Failed to load function from bytecode: (binary): cannot load incompatible bytecodeWarning: Failed to load function from bytecode: [string "..."]:2: unexpected symbol/usr/local/bin/luajit: /usr/local/share/lua/5.1/torch/File.lua:375: unknown object
```

I will try to generate the model by my side even if I a lot to learn and read. 
But, it will be awesome if you upload it again ;).

I'm very impressed about all have be done, and shared :) Thanks a lot ^^

**Comment by szagoruyko** [comment]
@gpolaert thanks for the feedback!
cc @soumith seems that https://github.com/torch/torch7/pull/748 didn't work?

**Comment by northeastsquare** [comment]
@szagoruyko , @gpolaert , @soumith If I use luajit, demo worked; But I train, out of memory, so I changed to plain  lua according to https://github.com/karpathy/char-rnn/issues/80, but the demo not work:

/home/sam/torch/install/bin/lua: /home/sam/torch/install/share/lua/5.1/torch/File.lua:301: Failed to load function from bytecode: binary string: bad header in precompiled chunk
stack traceback:
	[C]: in function 'error'
	/home/sam/torch/install/share/lua/5.1/torch/File.lua:301: in function 'readObject'
	/home/sam/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/sam/torch/install/share/lua/5.1/nn/Module.lua:158: in function 'read'
	/home/sam/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/sam/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/sam/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/sam/torch/install/share/lua/5.1/nn/Module.lua:158: in function 'read'
	/home/sam/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/sam/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/sam/torch/install/share/lua/5.1/nn/Module.lua:158: in function 'read'
	/home/sam/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/home/sam/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/home/sam/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	./demo.lua:36: in main chunk
	[C]: in function 'dofile'
	.../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: ?

**Comment by gpolaert** [comment]
Could you let me know the version used on sharpmask?

**Comment by northeastsquare** [comment]
I use these version, worked:
git clone -b v0.35.0  --depth 1 https://github.com/facebook/folly
    git clone -b v0.24.0  --depth 1 https://github.com/facebook/fbthrift
    git clone -b v1.0 https://github.com/facebook/thpp
    git clone -b v1.0 https://github.com/facebook/fblualib

**Comment by gpolaert** [comment]
Starting from scratch again seems to OK, excepted I'm running out of memory ;)
